<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/29
 * Time: 19:52
 */

namespace rabbit\illuminate\db;


use Illuminate\Database\ConnectionInterface;
use rabbit\core\Context;
use rabbit\core\ContextTrait;

/**
 * Class DbContext
 * @package rabbit\illuminate\db
 */
class DbContext extends Context
{
    /**
     * @param string $key
     * @return array|null
     */
    public static function getAll(?string $key = 'illuminate'): ?array
    {
        return parent::getAll($key); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $config
     * @param string $key
     */
    public static function setAll($config = [], ?string $key = 'illuminate'): void
    {
        parent::setAll($config, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param string $key
     * @return |null
     */
    public static function get(string $name, ?string $key = 'illuminate')
    {
        return parent::get($name, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param $value
     * @param string $key
     */
    public static function set(string $name, $value, ?string $key = 'illuminate'): void
    {
        parent::set($name, $value, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param string $key
     * @return bool
     */
    public static function has(string $name, ?string $key = 'illuminate'): bool
    {
        return parent::has($name, $key); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param string $key
     */
    public static function delete(string $name, ?string $key = 'illuminate'): void
    {
        parent::delete($name, $key);
    }

    /**
     *
     */
    public static function release(): void
    {
        $context = \Co::getContext();
        if (isset($context['illuminate'])) {
            /**
             * @var  $name
             * @var ConnectionInterface $connection
             */
            foreach ($context['illuminate'] as $name => $connection) {
                $connection->release(true, $name);
            }
        }
    }
}